-- KasurCanvas.com Database Schema & Seed Data
-- Generated for KasurCanvas.com Live Deployment

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(80) NOT NULL,
  `name` varchar(120) NOT NULL,
  `description` text DEFAULT NULL,
  `display_order` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `categories` (`id`, `slug`, `name`, `description`, `display_order`) VALUES ('1', 'duck-canvas', 'Cotton Duck Canvas', 'High-density plain weave natural and dyed canvas', '1');
INSERT INTO `categories` (`id`, `slug`, `name`, `description`, `display_order`) VALUES ('2', 'waterproof-waxed', 'Waterproof & Waxed Canvas', 'Treated weather-proof and water-shedding canvas', '2');
INSERT INTO `categories` (`id`, `slug`, `name`, `description`, `display_order`) VALUES ('3', 'industrial-technical', 'Industrial & Technical Fabrics', 'Conveyor, mechanical, and heavy utility textiles', '3');
INSERT INTO `categories` (`id`, `slug`, `name`, `description`, `display_order`) VALUES ('4', 'filtration-media', 'Filtration Media Cloth', 'High-performance liquid and dry filtration fabrics', '4');
INSERT INTO `categories` (`id`, `slug`, `name`, `description`, `display_order`) VALUES ('5', 'specialty-canvas', 'Specialty & Heritage Weaves', 'Dosuti, Ripstop, and protective contractor textiles', '5');

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_id` int(11) DEFAULT 1,
  `slug` varchar(120) NOT NULL,
  `title` varchar(200) NOT NULL,
  `subtitle` varchar(255) DEFAULT '',
  `badge_text` varchar(60) DEFAULT '',
  `short_desc` text NOT NULL,
  `full_desc` longtext NOT NULL,
  `weight_spec` varchar(150) DEFAULT '',
  `width_spec` varchar(150) DEFAULT '',
  `yarn_spec` varchar(150) DEFAULT '',
  `weave_spec` varchar(150) DEFAULT '',
  `finish_spec` varchar(150) DEFAULT '',
  `tensile_spec` varchar(150) DEFAULT '',
  `applications` text DEFAULT NULL,
  `features` text DEFAULT NULL,
  `is_featured` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('1', '1', 'cotton-duck-canvas-fabric', 'Pure Cotton Duck Canvas Fabric', 'Heavy-Duty 100% Virgin Cotton Plain-Weave Canvas (7oz - 28oz)', 'Bestseller', 'Manufactured with high-grade Pakistani combed cotton, our heavy-duty duck canvas offers superior tensile resilience, outstanding tear resistance, and a smooth, tightly woven face engineered for luggage, durable tents, artist boards, and rugged upholstery.', 'Crafted in our advanced Kasur manufacturing facility as part of Sabri Textiles\' vertically integrated textile production, this premium Cotton Duck Canvas represents the gold standard of natural utility fabrics. \n\nWoven from 100% pure virgin ring-spun cotton fibers on high-speed shuttleless air-jet looms, each yard features a meticulously balanced warp-and-weft intersection that delivers extraordinary dimensional stability. The fabric resists high-load friction, cyclic folding, and severe mechanical tension while remaining completely breathable.\n\nWhether left in its raw unbleached ecru tone for painters and eco-friendly tote manufacturers, or reactive-dyed to custom industrial pantones, Kasur Canvas duck is pre-shrunk, scoured, and checked under strict ISO-compliant quality protocols. Custom GSM specifications, roll widths, and specialty fire-retardant or mildew-inhibiting treatments are available upon export request.', '7 oz/yd² to 28 oz/yd² (240 GSM – 950 GSM)', '36 inches to 120 inches (up to 3.05 meters)', '10/2, 10/3, 7/2, 6/2, 4/2 ring-spun cotton', 'Tight Plain Weave / Numbered Duck (Single & Plied)', 'Natural Grey / Scoured / Bleached / Reactive Dyed', 'Warp: >1400 N | Weft: >1200 N (ASTM D5034)', '[\"Heavy-duty military and humanitarian relief tents\",\"Premium duffle bags, tool rolls, and canvas backpacks\",\"Architectural awnings, indoor upholstery, and slipcovers\",\"High-end artist stretched canvas panels\",\"Industrial machinery insulation jackets and wraps\"]', '[\"100% Pure Virgin Cotton Ring-Spun Yarns\",\"Flawless High-Density Plain Weave Structure\",\"Exceptional Abrasion & Puncture Resistance\",\"Natural Breathability and Skin-Friendly Softness\",\"Custom Widths available up to 120 inches\"]', '1', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('2', '2', 'waterproof-waxed-canvas-cloth', 'Heavy-Duty Waterproof Canvas Fabric', 'Paraffin & Fluorocarbon Treated Weather-Resistant Textile', 'Weatherproof', 'Treated with cutting-edge hydrophobic emulsion and traditional wax formulation, this heavy-duty canvas creates an impenetrable barrier against torrential rain, moisture penetration, and mold without sacrificing rugged flexibility.', 'Engineered specifically to conquer demanding outdoor environments, Kasur Canvas Waterproof Fabric pairs heavy-weight cotton duck with our proprietary weatherproof impregnating bath. \n\nUnlike synthetic plastic tarpaulins that sweat and crack under scorching sunlight, our breathable wax-treated cotton fabric lets micro-humidity escape while preventing external water droplets from penetrating. Rain beads up and glides right off the exterior, making it the preferred choice for long-term outdoor camping expeditions, defense shelters, truck covers, and maritime applications.\n\nEvery batch undergoes stringent hydrostatic pressure head testing in our Kasur laboratory. It is chemically stabilized against UV degradation, rotting in wet climates, and fungal mildew growth. Available in army olive green, deep khaki, desert tan, navy blue, and slate grey.', '12 oz/yd² to 24 oz/yd² (400 GSM – 820 GSM)', '48 inches to 96 inches', '10/2, 7/2, 6/2 heavy twisted cotton', 'High-Density 2x2 Duck Weave', 'Waxed / Hydrophobic PU Coating / Fluorocarbon / Water-Repellent', 'Hydrostatic Head: >800mm H2O | Tensile: >1600 N', '[\"Commercial truck tarpaulins and trailer cargo covers\",\"Severe-weather disaster relief and military camping tents\",\"Marine boat covers, deck tarps, and sail covers\",\"Agricultural grain harvest protection covers\",\"Vintage motorcycle bags and outdoor waxed apparel\"]', '[\"Extreme Hydrophobic Water Beading Performance\",\"Mold, Rot & Mildew Resistant Chemical Impregnation\",\"UV-Stabilized Against Prolonged Sun Exposure\",\"Zero Delamination: Long-lasting deep fiber infusion\",\"Reinforced Selvage Edges for High-Tension Rigging\"]', '1', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('3', '3', 'industrial-conveyor-belt-cloth', 'Industrial Conveyor Belt Canvas Cloth', 'High-Tenacity Cotton & Polyester Hybrid Mechanical Reinforcement Duck', 'Heavy Industrial', 'Designed for severe mechanical friction and continuous rotational torque, our industrial conveyor belt canvas combines dense cotton cushioning with high-tenacity synthetic yarns for conveyor plies and transmission systems.', 'Conveyor Belt Canvas by Kasur Canvas represents advanced mechanical textile engineering. Built inside our specialized heavy-weaving sheds in Kasur, this structural ply cloth forms the internal tensile core of industrial rubber conveyor belts, elevator bucket belts, and mechanical power transmission straps.\n\nBy interweaving high-tenacity polyester filament yarns in the longitudinal warp with multi-ply long-staple cotton yarns in the cross weft, the fabric delivers minimal elongation under tension while retaining superior rubber adhesion and mechanical fastener holding capability. \n\nIt exhibits supreme puncture resistance when handling coarse aggregates, ores, grain, or boxed freight. Specially heat-set and scoured to eliminate shrinkage variance and prevent belt delamination in continuous 24/7 conveyor operations.', '18 oz/yd² to 36 oz/yd² (610 GSM – 1220 GSM)', '24 inches to 84 inches (Custom slit widths available)', 'High Tenacity EP (Polyester / Cotton) Plied Yarns', 'Heavy Multi-Ply Industrial Duck Weave', 'Heat-set, Scoured, RFL Rubber-Adhesion Ready', 'Warp: >3200 N | Weft: >2100 N | Elongation: <3.5%', '[\"Rubber conveyor belts for cement, mining, and quarry plants\",\"Industrial bucket elevator belt reinforcement\",\"Flat mechanical power transmission belts\",\"Heavy-load packaging sorting lines and logistics hubs\",\"Agricultural harvester and baler belts\"]', '[\"Ultra-Low Elongation Under Continuous Heavy Load\",\"Exceptional Inter-Ply Rubber & PVC Adhesion Strength\",\"High Fatigue Life Under Repeated Drum Flexing\",\"Thermal Resistance to Frictional Heat Buildup\",\"Consistent Gauge and Roll Thickness Accuracy\"]', '1', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('4', '5', 'dosuti-double-yarn-cotton-cloth', 'Authentic Dosuti Cloth (Double Cotton Yarn)', 'Traditional 2-Ply Warp & Weft Breathable Textile (Do-Suti)', 'Pakistani Heritage', 'Honoring Pakistan\'s storied textile heritage, Dosuti (meaning \"Two-Thread\") cloth pairs two yarns running simultaneously in warp and weft, yielding a supremely durable, breathable, and distinctively textured cotton fabric.', 'Named after the historic South Asian weaving tradition (\'Do\' meaning Two, \'Suti\' meaning Cotton Threads), Dosuti Cloth has been manufactured in Kasur for generations. At Kasur Canvas, we have upgraded this authentic artisanal fabric with computerized loom accuracy while preserving its organic soul.\n\nBy running twin-plied yarns together in both the warp and weft directions, Dosuti achieves a unique double-density grid structure. It combines high tear resistance with an open, airy breathability that synthetic fabrics simply cannot replicate. \n\nIt is extensively exported across South Asia, the Middle East, and Europe for industrial flour and grain sacks, rustic safari tent linings, durable workwear uniforms, traditional shoe linings, and utility bags. It softens delightfully with washing while remaining nearly impossible to rip.', '8 oz/yd² to 16 oz/yd² (270 GSM – 540 GSM)', '36 inches to 72 inches', '10/1 x 10/1 Double or 12/2 Twin Plied Cotton', 'Traditional Double-Yarn Plain Weave (2x2 Structure)', 'Raw Ecru / Semi-Bleached / Dyed / Soft Finish', 'Warp: >950 N | Weft: >900 N', '[\"Heavy-duty commercial flour, pulse, and grain packaging sacks\",\"Safari tent inner liners, luxury glamping curtains, and drapes\",\"Durable industrial uniforms, work aprons, and pocket linings\",\"Canvas espadrille and sneaker footwear internal lining\",\"Organic reusable shopping bags and tote carriers\"]', '[\"Authentic 2-Ply Double Yarn Warp and Weft Weaving\",\"High Air Permeability with Rugged Surface Strength\",\"100% Eco-Friendly Biodegradable Cotton Composition\",\"Softens with Use Without Structural Integrity Loss\",\"Natural Resistance to Fiber Slippage and Seam Puckering\"]', '1', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('5', '4', 'industrial-filter-cloth-media', 'Precision Industrial Filter Cloth', 'Engineered Pure Cotton, Polyester & Blended Liquid-Solid Separation Media', 'High Precision', 'Engineered for press filters, centrifuges, and rotary drum systems, our filter fabrics deliver exact micron pore ratings, high chemical resilience, and rapid filter cake discharge across chemical, mining, and food processing plants.', 'Backed by Sabri Textiles\' 50+ year legacy in industrial filtration fabrics, Kasur Canvas manufactures high-precision filter media calibrated for critical solid-liquid and dry dust separation processes.\n\nAvailable in 100% pure long-staple cotton, high-tenacity filament polyester, or specialized poly-cotton hybrid blends, each filter roll is woven under controlled yarn tension to ensure uniform micron porosity across every square inch. \n\nIn wet slurry filtration (such as sugar juice clarification, chemical precipitation, effluent wastewater treatment, and mining mineral beneficiation), our fabrics offer smooth particle release, minimal blinding/clogging, and resistance to aggressive chemical slurries and thermal pressure cycles.', '10 oz/yd² to 26 oz/yd² (340 GSM – 880 GSM)', '30 inches to 90 inches', 'Spun Cotton, Multifilament Polyester, Monofilament Hybrid', 'Twill, Plain, and Satin Filter Weaves', 'Heat-Set, Calendered Smooth Surface, Singed', 'Air Permeability: 5 - 250 L/dm²/min | Bursting: >3.2 MPa', '[\"Plate and frame filter presses in sugar refineries and mills\",\"Municipal and industrial wastewater treatment plants\",\"Chemical, pharmaceutical, and dye pigment filtration\",\"Mining slurry dewatering and mineral recovery presses\",\"Food oil clarification and beverage manufacturing\"]', '[\"Precision-Calibrated Micron Porosity & High Flow Rates\",\"Smooth Calendered Finish for Instant Filter Cake Release\",\"Resistance to Acidic, Alkaline, and Hot Slurry Baths\",\"Zero Fiber Shedding in Sensitive Food and Pharma Media\",\"Custom Laser-Cut Filter Press Cloths with Hemmed Eyelets\"]', '0', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('6', '5', 'canvas-drop-cloth-dust-sheet', 'AAA Grade Canvas Drop Cloth (Dust Sheet)', 'Professional Contractor Grade 100% Cotton Painter Drop Sheets', 'Contractor Grade', 'Made from premium Triple-AAA duck canvas with double-stitched rot-resistant hems, our contractor drop cloths trap paint splatters, absorb spills instantly, and protect expensive hardwood and tile flooring during renovations.', 'Designed for commercial decorators, painters, and home renovation professionals, Kasur Canvas Drop Cloths are fabricated from durable 100% natural cotton canvas. Unlike hazardous plastic drop sheets that tear easily, create slip hazards, and let wet paint smear around, our heavy-gauge cotton canvas absorbs paint droplets immediately.\n\nEvery drop sheet features quadruple-fold perimeter hems sewn with heavy polyester thread to prevent fraying through dozens of commercial washing cycles. The heavy fabric drapes flat over furniture, stairs, and hardwood floors without curling at the corners.\n\nAvailable in standard export sizes (6ft x 9ft, 9ft x 12ft, 12ft x 15ft, and long hallway runners) with private-label retail packaging available for international hardware and DIY retail chains.', '6 oz, 8 oz, 10 oz, and 12 oz per square yard', 'Finished Sizes: 4x12ft, 4x15ft, 6x9ft, 9x12ft, 12x15ft', '100% Natural Unbleached Cotton', 'Dense Seamless Plain Weave Duck', 'Washed Natural / Double Folded Hems / No Odor', 'Heavy Tear Resistance | 100% Machine Washable', '[\"Commercial painting, drywall, and plastering floor shielding\",\"Furniture dust draping during construction and remodeling\",\"DIY curtains, rustic outdoor tablecloths, and photo backdrops\",\"Automotive mechanic fender and seat grease covers\",\"Contractor jobsite entryway dirt control mats\"]', '[\"Super Absorbent Cotton Stops Wet Paint Tracking\",\"Heavyweight Non-Slip Fabric Stays Firmly in Place\",\"Quadruple-Fold Double Lockstitched Edge Hems\",\"Washable, Reusable, and Environmentally Sustainable\",\"Retail-Ready Barcoded Polybag Packaging Available\"]', '0', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('7', '5', 'tactical-ripstop-canvas-fabric', 'High-Performance Tactical RipStop Canvas', 'Crosshatch Reinforced Tear-Stopping Cotton-Poly Combat Textile', 'Ultra Rugged', 'Featuring a visible square grid of high-tenacity reinforcement threads interwoven throughout the base canvas, this tactical fabric halts punctures and rips in their tracks, engineered for extreme military, overland, and expedition applications.', 'When ordinary canvas falls short against barbed wire, rock abrasions, and extreme mechanical stress, Kasur Canvas Tactical RipStop delivers unmatched durability. \n\nWoven with a distinctive box-grid pattern where ultra-strong plied reinforcement cords cross at tight 5mm intervals, any accidental tear or puncture is stopped dead at the nearest grid seam. The fabric cannot propagate a rip even under tremendous hurricane wind shear.\n\nTreated with fluorocarbon weather repelling agents and matte military-spec dyeing, it is trusted for heavy expedition luggage, 4WD rooftop overland tents, tactical vests, canopy sidewalls, and military rucksacks. Lightweight yet practically indestructible.', '10 oz/yd² to 18 oz/yd² (340 GSM – 610 GSM)', '54 inches to 65 inches', 'Cotton / High-Tenacity Poly Blend with Core-Spun Grid', 'Reinforced Crosshatch Square RipStop Grid', 'Water Repellent (DWR), Anti-UV, Anti-Mildew, Matte Finish', 'Tear Strength: >240 N (Elmendorf) | Tensile: >1900 N', '[\"Tactical military backpacks, pouches, and load-bearing gear\",\"Overland 4x4 vehicle rooftop tents and roll-out awnings\",\"Heavy-duty industrial protective work jackets and trousers\",\"Helicopter covers, aerospace cargo tarps, and field shelters\",\"Extreme mountaineering duffels and expedition hammocks\"]', '[\"Integrated Crosshatch Grid Halts Tears Instantly\",\"Superior Strength-to-Weight Ratio Over Plain Ducks\",\"Extreme Wind Shear and Abrasion Endurance\",\"Durable Water Repellent (DWR) Hydrophobic Finish\",\"Available in Olive Drab, Coyote Tan, Black, and Navy\"]', '1', '2026-09-04 01:41:41');
INSERT INTO `products` (`id`, `category_id`, `slug`, `title`, `subtitle`, `badge_text`, `short_desc`, `full_desc`, `weight_spec`, `width_spec`, `yarn_spec`, `weave_spec`, `finish_spec`, `tensile_spec`, `applications`, `features`, `is_featured`, `created_at`) VALUES ('8', '3', 'cabinet-roll-towels-crt-fabric', 'Continuous Roll Toweling (CRT) Fabric', 'Commercial Grade 100% Loop-Cotton Roll Hand-Drying Textile', 'Commercial Hygiene', 'Engineered for commercial washroom roller dispensers, this heavy continuous cotton toweling delivers superior water absorption, high laundry turn endurance, and lint-free hand drying for high-traffic institutions.', 'Part of Sabri Textiles\' specialty toweling and canvas export lines, our Cabinet Roll Towel (CRT) fabric is woven for the international commercial hygiene and linen rental sector.\n\nEngineered to endure 80+ aggressive commercial wash cycles, this 100% cotton fabric features specialized low-lint loop structures and reinforced selvages that feed smoothly through mechanical and automatic cabinet towel dispensers. \n\nColored boundary identification stripes (blue or red yarn edge markers) facilitate sorting and inspection in commercial laundries. It delivers a much more sustainable, waste-free, and luxurious hand-drying experience than disposable paper towels.', '7.5 oz/yd² to 11 oz/yd² (250 GSM – 380 GSM)', '10.5 inches to 12.5 inches (Standard Cabinet Roll Widths)', '100% Combed Cotton Ring Spun Yarns', 'Engineered Absorbent Textured Towel Weave with Selvage Locks', 'Optic Bleached White with Colored ID Border Stripes', 'Wash Durability: >80 Commercial High-Temp Cycles', '[\"Commercial washroom roller cabinet towel dispensers\",\"Industrial linen rental and contract laundering operations\",\"Hospital, laboratory, and clean manufacturing hand hygiene\",\"Heavy-duty industrial wiping and tool drying rolls\"]', '[\"Instant Water Absorbency from First Touch\",\"Ultra-Low Lint Release During Roller Feeding\",\"Heavy Commercial Wash Life Cycle Endurance\",\"Precision Slit and Clean Bound Selvages Prevent Jams\",\"Colored Woven ID Marker Threads for Laundry Sorting\"]', '0', '2026-09-04 01:41:41');

DROP TABLE IF EXISTS `product_images`;
CREATE TABLE `product_images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `caption` varchar(200) DEFAULT '',
  `is_primary` tinyint(1) DEFAULT 0,
  `display_order` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `product_id` (`product_id`),
  CONSTRAINT `product_images_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('1', '1', 'assets/images/products/cotton-duck-1.jpg', 'Premium Natural Cotton Duck Canvas Roll', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('2', '1', 'assets/images/products/cotton-duck-2.jpg', 'High-Density Warp & Weft Yarn Weave Detail', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('3', '1', 'assets/images/products/cotton-duck-3.jpg', 'Dyed and Natural Canvas Warehouse Inventory', '0', '3');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('4', '2', 'assets/images/products/waterproof-canvas-1.jpg', 'Extreme Hydrophobic Water Droplet Beading on Olive Canvas', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('5', '2', 'assets/images/products/waterproof-canvas-2.jpg', 'Heavy-Duty Reinforced Stitching and Solid Brass Grommets', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('6', '2', 'assets/images/products/waterproof-canvas-3.jpg', 'Export-Ready Rolls of Waterproof Canvas Fabric', '0', '3');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('7', '3', 'assets/images/products/conveyor-canvas-1.jpg', 'Heavy Industrial Multi-Ply Conveyor Canvas Roll in Facility', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('8', '3', 'assets/images/products/conveyor-canvas-2.jpg', 'Cross-Section & Dense Multi-Twist Yarn Structure', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('9', '4', 'assets/images/products/dosuti-cloth-1.jpg', 'Authentic Unbleached Dosuti Double-Thread Cotton Bolt', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('10', '4', 'assets/images/products/dosuti-cloth-2.jpg', 'Close-up Inspection of Double Yarn Construction', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('11', '5', 'assets/images/products/filter-cloth-1.jpg', 'Cleanroom Grade Industrial Filter Cloth Media Roll', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('12', '5', 'assets/images/products/filter-cloth-2.jpg', 'Micro-Porous Precision Weave Surface View', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('13', '6', 'assets/images/products/canvas-drop-cloth-1.jpg', 'Professional Grade Folded Canvas Drop Sheet with Paint Tools', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('14', '6', 'assets/images/products/canvas-drop-cloth-2.jpg', 'Reinforced Double-Stitched Edge Hem Detail', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('15', '7', 'assets/images/products/ripstop-canvas-1.jpg', 'Tactical Olive RipStop Canvas Bolt with Grid Weave Pattern', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('16', '7', 'assets/images/products/ripstop-canvas-2.jpg', 'Macro Close-Up of Crosshatch High-Tenacity Reinforced Grid', '0', '2');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('17', '7', 'assets/images/products/ripstop-canvas-3.jpg', 'High Capacity Canvas Warehouse Finished Stocks', '0', '3');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('18', '8', 'assets/images/products/continuous-roll-towel-1.jpg', 'Stacked Commercial Continuous Roll Towel Bolts with Blue Edge', '1', '1');
INSERT INTO `product_images` (`id`, `product_id`, `image_url`, `caption`, `is_primary`, `display_order`) VALUES ('19', '8', 'assets/images/products/continuous-roll-towel-2.jpg', 'High-Absorbency Woven Cotton Loop Structure', '0', '2');

DROP TABLE IF EXISTS `inquiries`;
CREATE TABLE `inquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(150) DEFAULT 'General Inquiry',
  `customer_name` varchar(120) NOT NULL,
  `company_name` varchar(150) DEFAULT '',
  `email` varchar(150) NOT NULL,
  `phone` varchar(80) DEFAULT '',
  `country` varchar(100) DEFAULT 'Pakistan',
  `quantity` varchar(100) DEFAULT '',
  `message` text NOT NULL,
  `status` enum('new','in_review','quoted','completed') DEFAULT 'new',
  `ip_address` varchar(50) DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `inquiries` (`id`, `product_name`, `customer_name`, `company_name`, `email`, `phone`, `country`, `quantity`, `message`, `status`, `ip_address`, `created_at`) VALUES ('1', 'Pure Cotton Duck Canvas Fabric', 'Alexander Wright', 'Alpine Expedition Gear UK', 'alexander@alpinegear.co.uk', '+44 20 7946 0991', 'United Kingdom', '15,000 Meters', 'Requesting CIF Liverpool quote for 18oz waterproofed duck canvas.', 'new', '127.0.0.1', '2026-09-04 02:01:53');

SET FOREIGN_KEY_CHECKS=1;
